### PR TITLE
Change text input to date input

### PR DESCRIPTION
**Pull request by TomNUSDS**
Simple, quick fix to make input field an html5 date input field. We should use a 508 compliant DateInput component, but this the html5 picker is better than just a plain text input for now.

Part of issue #101

### CODE REVIEW

**Comment by dmethvin-gov** [comment]
Note that the internal format of the data will be `yyyy-mm-dd` (ISO8601) but the displayed format depends on the browser's locale. I'd hope/think that the user's format would be `mm/dd/yyyy` but it might be worthwhile verifying that. Also I'm not sure where (or if) we've standardized converting from strings to an internal format like `moment`, or perhaps we don't need to. Note that if we do use an internal format we want to use UTC (even if just for the date) because otherwise the date might not display correctly in all time zones. With all that said it seems like this is better than what we have.

**Comment by benwarfield-usds** [comment]
The back-end view of this is a LocalDate, which is to say a date with neither time nor time zone. I would expect that to travel back and forth to the server as an ISO date, but that does not appear to be what's happening right now, so merging this without a further shim would probably break something.

**Comment by dmethvin-gov** [comment]
> The back-end view of this is a LocalDate ... I would expect that to travel back and forth to the server as an ISO date, but that does not appear to be what's happening right now

I hate dates _so much_. I've spent days trying to deal with this problem on multiple projects over the years. The most reliable thing I've found is to keep it in ISO8601 format measured from UTC as a string, which still gives correct comparisons. 

A local date should be in the local time zone, but "local" isn't a very meaningful word in the cloud. Can we send you ISO dates as strings that you can ensure stay in UTC?

**Comment by benwarfield-usds** [comment]
I mean, I'm not going to argue with you about how they should have named things in the `java.time` package—I just want to be clear that the date that you generate from the date picker is stored as a year-month-day tuple with neither time nor time zone. 

Generated timestamps are stored as timestamps (though we could if desired convert them from UTC to a time zone specified in the graphql request), but those aren't what we're talking about here.

**Comment by dmethvin-gov** [comment]
Yeah, from the graphql it looks like we are [just sending dates as strings](https://github.com/CDCgov/prime-data-input-client/blob/d4cbdde76ab0651a916fb6f36ae4973afb92beee/frontend/src/app/patients/PatientForm.jsx#L26). If the string isn't in `mm/dd/yyyy` graphql says it saved but there's actually an internal server error reported from the backend, no doubt because [it's parsing that format](https://github.com/CDCgov/prime-data-input-client/blob/d4cbdde76ab0651a916fb6f36ae4973afb92beee/backend/src/main/java/gov/cdc/usds/simplereport/api/patient/PatientMutationResolver.java#L16). 

I believe the default format for Java's `LocalDate` is ISO8601 so parsing that would just require removing the custom parser/formatter there. At that point the frontend would need to ensure all dates are in that format and we'd need to coordinate with backend deploy. The PR here takes care of the locale formatting, so I think we'd be okay.

**Comment by benwarfield-usds** [comment]
I can probably get the back end to play nicely with both formats on the receiving end--reliably emitting the right thing might be a little harder. At this point I think we have a bunch of problems like this, though--I'm a little worried about pulling on threads right this minute.

**Pull request merged**
