### PR TITLE
Notification refactors - Ready for review

### PR DESCRIPTION
**Pull request by sharmaneil**
# Issue
Not tracked, but this coincidentally addresses the bug in: 
https://github.com/CDCgov/prime-central/issues/80

# About

Lots of small things:
- notifications are no longer in redux. This cleans out a lot of code
- using [React Toastify](https://github.com/fkhadra/react-toastify)
- see behavior below

## 1. Notifications are global and survive page changes.
global-notifications

---
---

## 2. Clicking on a notification closes it (otherwise it closes in 4 seconds on its own)
close-notification

---
---

## 3. Only one notification can be displayed at a time. New notifications force out the existing ones (if there are any)
competing-notifications

### CODE REVIEW

**Comment by sharmaneil** [comment]
Actually, i'm not sure if this is complete. 

Since notifications are now a top-level thing in redux, adding a notification on another page would simply grab the existing notification and render that. It might need to be keyed by page

**Comment by sharmaneil** [comment]
Hmm, i think this is a sub-optimal design. Perhaps notifications shouldn't go in redux

In general, a user action should trigger a notification. Ie: adding/removing from a queue -> show notification.

Right now, if a component renders while a notification is in redux, the notification shows, even if the user didn't make an action on the page.

**Comment by sharmaneil** [comment]
Probably going to try out: https://fkhadra.github.io/react-toastify/introduction instead of rolling our own.

**Comment by sharmaneil** [comment]
It works! I think this solution is much better, but I'm having trouble doing the merge conflicts. Maybe after a nap it'll work

**Comment by sharmaneil** [comment]
@benwarfield-usds i think i managed to merge in your aoe work without breaking things, but there were a lot of conflicts. Mind doing a once over to make sure it works as expected?

The only issue I'm seeing is the "Submit Anyway" button needs to be clicked twice to actually do the submission, but that is a problem on main too so it could be fixed in another PR.
Screen Shot 2020-11-07 at 1 51 48 PM

**Comment by benwarfield-usds** [comment]
Yeah, more precisely the dialog box needs to be clicked to give it focus, then the button to actually activate it. Were all of this code not both urgently needed for user testing _and_ on the bubble for rewriting, I would have spent some time trying to fix that, but it seemed like the wrong investment last night.

**Comment by hmyers-cms** [comment]
I like the interactions! All the behaviors you listed out look good. Only thing I'm seeing is that I had added a green outline around the entire alert, to help it stand out more (light green on light gray blends in a bit). Looks like that CSS got eliminated along w/ my css animation.  Should be `outline: 2px solid #00a91c;`

**Review by timothybest-usds — APPROVED** [review]

**Comment by sharmaneil** [comment]
@hmyers-cms 

Nice catch. I fixed it, but the outline pixels aren't quite perfect. Probably good enough for now:
Screen Shot 2020-11-10 at 11 56 41 AM

The notification library i used had its own out-of-the-box animations, so I used one of them. I liked yours better though, but didn't go into creating a custom one. If you feel it necessary, you can create custom ones:
https://fkhadra.github.io/react-toastify/custom-transition/

**Comment by sharmaneil** [comment]
I'm going to go ahead and merge this before there are more conflicts.

**Pull request merged**
