### PR TITLE
Fixed broken deserialization of JSON-serialized Person  objects

### PR DESCRIPTION
**Pull request by benwarfield-usds**
Wrote a small converter function accepts either a single-element JSON array or a String JSON node, and returns the desired string value, and wrapped it around the deserialization of "race". This will allow us to get rid of the "NoJson" read-only classes, and also prevent this bug from showing up in any more weird corners.

### CODE REVIEW

**Comment by benwarfield-usds** [comment]
@nickrobison-usds you're gonna _love_ this one 😁

**Comment by timothybest-usds** [comment]
https://github.com/CDCgov/prime-data-input-client/issues/222

**Review by timothybest-usds — APPROVED** [review]

**Comment by benwarfield-usds** [comment]
Should probably add a regression test using stored JSON files.

**Review by nickrobison-usds — APPROVED** [review]
I love it! Ahh..... the smell of freshly mown code in the morning, nothing like it.

**Comment by benwarfield-usds** [comment]
And then I had to spoil it by adding a bunch of test code. Oh well. 😜

**Pull request merged**
