### PR TITLE
Frontend support for a single facility in the style of multiple facilities

### PR DESCRIPTION
**Pull request by timothybest-usds**
This PR implements the frontend support for multiple facilities. Note: most API calls will need to be updated and disabled inputs/buttons will need to be implemented when we have backend support for multiple facilities.

Screen Shot 2020-12-07 at 11 50 35 AM
Screen Shot 2020-12-07 at 11 50 28 AM
Screenshot_2020-12-07 SimpleReport

### CODE REVIEW

**Comment by timothybest-usds** [comment]
converting this back to a draft to rebase off of benwarfield-usds/persist-multiple-facilities

**Comment by benwarfield-usds** [comment]
This seems to make it impossible to change the name of a facility?

**Comment by timothybest-usds** [comment]
Why is it impossible to change the name of a facility? (Note: disabled form fields were removed after database support for facilities)

**Comment by benwarfield-usds** [comment]
I think based on subsequent conversations that I misunderstood how two pieces of code were interacting. 😑

**Pull request merged**
