### PR TITLE
dev graphql implementation

### PR DESCRIPTION
**Pull request by pete-usds**
Reference: https://github.com/CDCgov/prime-central/issues/116

This ticket contains a *bare minimum* development structure of GraphQL for our current patient and device implementations. It includes the default demo data, the ability to query this data via GraphQL, and the ability to add new patients and devices via the same. Adding devices or patients in this way are done in LOCALSTORAGE - there is no permanent datastore.

It's intended to be a placeholder for front end development for now.

### CODE REVIEW

**Comment by sharmaneil** [comment]
I support this approach until a locally-running backend + database can replace it. It unblocks the frontend. Was going to set this up myself today, thanks pete!

**Comment by sharmaneil** [comment]
Responding to your comment on slack: https://usds.slack.com/archives/C01B2LH9B3P/p1604940020168700?thread_ts=1604939688.167800&cid=C01B2LH9B3P

If I understand this correctly (i might not), i think the apollo graphql inmemory cache is somewhat of a redux competitor, not a localStorage competitor. If you refresh the page, you'd still lose all your data.

https://stackoverflow.com/questions/59891325/apollo-client-cache-vs-redux

**Comment by sharmaneil** [comment]
Do you have a sense of how the data would flow between the frontend (redux/apollo/localstorage) and backend?


My high-level thoughts (not sure how this would look like in code):

#### Scenario 1: User opens the app for the first time:
App makes one or multiple graphql queries for data -> response data goes in redux -> redux updates localstorage and triggers the app to re-render with the data

### Scenario 2: User visits the app again
App data loads data from local storage to redux -> App makes one or multiple graphql queries for *new* data -> updated data goes in redux -> redux updates the app and localstorage 

#### Scenario 3: User wants to update/submit a thing:
User makes graphql query -> response data goes in redux -> update localstorage + re-render app

**Comment by pete-usds** [comment]
I think Apollo basically handles all that so you don't need to worry about it. https://www.apollographql.com/docs/react/why-apollo/

```
You'll find that when you switch to Apollo Client, you'll be able to delete a lot of unnecessary code related to data management. The exact amount will vary depending on your application, but some teams have reported up to thousands of lines
```

Check Zero Config Cache / etc.

(yeah I'm still trying to steer us away from a REST API based data transfer process...  lol)

**Comment by pete-usds** [comment]
Most of this will fly away long term but just to have it in the branch for now...

**Pull request merged**
